blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Support / Questions
    url: https://github.com/nerzors/seimgconverter/discussions
    about: Please use Discussions for questions, ideas, or help.
