blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Support / Questions
    url: https://github.com/<YOURUSER>/<YOURREPO>/discussions
    about: Please use Discussions for questions, ideas, or help.
